parameters:



services:
    youshopify.service:
        class: Shopify\AdminBundle\Service\YouShopifyService
    client.service:
        class: Shopify\AdminBundle\Service\ClientService
    wcurl.service:
        class: Shopify\AdminBundle\Service\WcurlService